<div id="productContainer" class="product-container">

</div>
<div class="button-container">
    <div id="loading"><img src="http://localhost/magento/skin/frontend/pbtheme/default/images/Loading.gif" alt="loading...." /></div>
    <button id="loadMoreBtn" class="load-more-btn"><span>Load More</span></button>
</div>


<button id="loadMoreBtn" class="load-more-btn"><span>Load More </span></button></div>