 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 <div class="toolbar">
      <span id="Hamberger-icon" class="hamberger-icon" onclick="openNav()">&#9776;</span>
      <div class="pb-img">
          <img class="pb" src="https://d1jbf5z8givhnm.cloudfront.net/skin/frontend/unifiedtheme/default/images/pblogo_bold_v3.png" alt="PipaBela" height="50px;">
      </div>
 </div>

 <div class="topnav" id="Topnav">
     <a href="product-list">What's New</a>
     <a href="product-list">Shop By Category</a>
     <a href="product-list">Shop By Collection</a>
     <a href="product-list">Shop By Material</a>
     <a href="product-list">Shop By Price</a> 
     <a href="product-list">Shop By Material</a>
     <a href="product-list">Create your jewellery</a>
     <a href="product-list">Rakhi</a>
 </div>


 <div id="Sidenav" class="sidenav">
     <a href="#" class="closebtn" onclick="closeNav()">&times;</a>
     <a href="product-list">What's New</a>
     <a href="product-list">Shop By Category</a>
     <a href="product-list">Shop By Collection</a>
     <a href="product-list">Shop By Material</a>
     <a href="product-list">Shop By Price</a>
     <a href="product-list">Shop By Material</a>
     <a href="product-list">Create your jewellery</a>
     <a href="product-list">Rakhi</a>
 </div> 
